### PR TITLE
Fix comment color same with colorcolumn

### PR DESCRIPTION
**Pull request by krehwell**
I use color hex which every man loves. that color only for applied to comment

### CODE REVIEW

**Comment by pbrisbin** [comment]
Nice, thanks. Can I see a new screenshot?

**Comment by krehwell** [comment]
here you go
image of new off colorscheme

_if bg is slightly different it is because I am using tranparent bg for vim so it uses the terminal bg instead._

**Comment by pbrisbin** [comment]
Looks beautiful, thanks!

**Comment by krehwell** [comment]
cool, glad you like it. thanks for merged it too :)

**Pull request merged**
